// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkakqfxmrovyodrkvxkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYWtxZnhtcm92eW9kcmt2eGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTU1MTgsImV4cCI6MjA2NzU3MTUxOH0.ssBvuCGmzvd4S70O8HDa5aYQr11aRLLol2GIX5a8GiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});